# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19h5AfiAZBlEb8hdvCKaL3wAScvEgyh0S
"""

import streamlit as st
from conecta_v1 import QASystem  # Importe seu módulo de chatbot
from CRUD import autenticar_usuario  # Importe o CRUD

# Configuração da página
st.set_page_config(page_title="Chatbot Conecta", page_icon="🤖")

# 1. Tela de Login
if "user_id" not in st.session_state:
    st.title("Login")
    email = st.text_input("Email")
    password = st.text_input("Senha", type="password")

    if st.button("Entrar"):
        user = autenticar_usuario(email, password)
        if user:
            st.session_state.user_id = str(user["_id"])  # Armazena o ID do usuário
            st.success("Login bem-sucedido!")
        else:
            st.error("Email ou senha incorretos.")

# 2. Chatbot (só aparece se logado)
else:
    st.title("Chatbot Conecta 🤖")

    # Inicializa o chatbot
    qa = QASystem()

    # Histórico de mensagens
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Exibe mensagens anteriores
    for msg in st.session_state.messages:
        st.chat_message(msg["role"]).write(msg["content"])

    # Input do usuário
    user_input = st.chat_input("Pergunte algo sobre marketplaces...")
    if user_input:
        # Adiciona pergunta ao histórico
        st.session_state.messages.append({"role": "user", "content": user_input})
        st.chat_message("user").write(user_input)

        # Busca resposta
        resposta = qa.ask_question(user_input, st.session_state.user_id)

        # Exibe resposta
        st.session_state.messages.append({"role": "assistant", "content": resposta["resposta"]})
        st.chat_message("assistant").write(resposta["resposta"])